name: EFS-Backup

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  EFS-Backup:
    runs-on: ubuntu-latest

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::058264262021:role/githubaction-aws-identity-role
          role-session-name: AssumeRoleWithWebIdentity
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EFS Backup
        id: create_backup
        run: |
          BACKUP_JOB_ID=$(aws backup start-backup-job \
            --backup-vault-name "EFS_backup_vault" \
            --resource-arn "arn:aws:elasticfilesystem:ap-south-1:058264262021:file-system/fs-0c7630c295e6d5b45" \
            --iam-role-arn "arn:aws:iam::058264262021:role/service-role/AWSBackupDefaultServiceRole" \
            --region "ap-south-1" \
            --query 'BackupJobId' \
            --output text)
          echo "Backup Job ID: $BACKUP_JOB_ID"
          echo "::set-output name=backup_job_id::$BACKUP_JOB_ID"

      - name: Tag Backup for Retention
        run: |
          BACKUP_JOB_ID=${{ steps.create_backup.outputs.backup_job_id }}
          aws backup tag-resource \
            --resource-arn "arn:aws:backup:${{ secrets.AWS_REGION }}:backup-job/$BACKUP_JOB_ID" \
            --tags Retention=1

      - name: Cleanup Old Backups
        run: |
          aws backup list-backup-jobs \
            --backup-vault-name "EFS_backup_vault" \
            --query 'BackupJobs[?CompletionDate<`date -d "1 day ago" -u +%Y-%m-%dT%H:%M:%S`].BackupJobId' \
            --output text | while read backup_job_id; do
              aws backup delete-backup \
                --backup-job-id "$backup_job_id"
            done
