name: EFS-Backup

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  EFS-Backup:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EFS Backup
        id: create_backup
        run: |
          BACKUP_JOB_ID=$(aws backup start-backup-job \
            --backup-vault-name "EFS_backup_vault" \
            --resource-arn "arn:aws:elasticfilesystem:ap-south-1:058264262021:file-system/fs-0c7630c295e6d5b45" \
            --iam-role-arn "arn:aws:iam::058264262021:role/githubactions_aws_role" \
            --region "ap-south-1" \
            --query 'BackupJobId' \
            --output text)
          echo "Backup Job ID: $BACKUP_JOB_ID"
          echo "::set-output name=backup_job_id::$BACKUP_JOB_ID"

      - name: Get Recovery Point ARN
        run: |
          BACKUP_JOB_ID=${{ steps.create_backup.outputs.backup_job_id }}
          RECOVERY_POINT_ARN=$(aws backup describe-backup-job --backup-job-id $BACKUP_JOB_ID --query 'BackupJob.RecoveryPoints[0].RecoveryPointArn' --output text)
          echo "Recovery Point ARN: $RECOVERY_POINT_ARN"
          echo "::set-output name=recovery_point_arn::$RECOVERY_POINT_ARN"
