name: EFS-Backup

on:
  workflow_dispatch:

permissions:
  id-token: write  # This is required for requesting the JWT contents
  contents: read   # This is required for actions/checkout (if used)

jobs:
  EFS-Backup:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EFS Backup
        id: create_backup
        run: |
          BACKUP_JOB_ID=$(aws backup start-backup-job \
            --backup-vault-name "EFS_backup_vault" \
            --resource-arn "arn:aws:elasticfilesystem:ap-south-1:058264262021:file-system/fs-0c7630c295e6d5b45" \
            --iam-role-arn "arn:aws:iam::058264262021:role/githubactions_aws_role" \
            --region "ap-south-1" \
            --query 'BackupJobId' \
            --output text)
          echo "Backup Job ID: $BACKUP_JOB_ID"
          echo "BACKUP_JOB_ID=$BACKUP_JOB_ID" >> $GITHUB_ENV

      - name: Check Backup Job Status
        run: |
          BACKUP_JOB_ID=${{ env.BACKUP_JOB_ID }}
          STATUS=$(aws backup describe-backup-job --backup-job-id $BACKUP_JOB_ID --query 'BackupJob.BackupStatus' --output text)
          if [[ "$STATUS" != "COMPLETED" ]]; then
            echo "Backup job not completed yet. Retrying in 5 minutes..."
            exit 1
          fi

      - name: Get Recovery Point ARN
        run: |
          BACKUP_JOB_ID=${{ env.BACKUP_JOB_ID }}
          RECOVERY_POINT_ARN=$(aws backup describe-backup-job --backup-job-id $BACKUP_JOB_ID --query 'BackupJob.RecoveryPoints[0].RecoveryPointArn' --output text)
          echo "Recovery Point ARN: $RECOVERY_POINT_ARN"
          echo "RECOVERY_POINT_ARN=$RECOVERY_POINT_ARN" >> $GITHUB_ENV

      - name: Tag Recovery Point for Retention
        run: |
          RECOVERY_POINT_ARN=${{ env.RECOVERY_POINT_ARN }}
          aws backup tag-resource --resource-arn "$RECOVERY_POINT_ARN" --tags Retention=1
